### ISSUE TITLE
راهنما بروز نیست و این بسته با توجه به راهنما کار نمی‌کند

### ISSUE THREAD

**Issue by mojtaba82** [pamenary/LaravelSms#4]
راهنما بروز نیست و این بسته با توجه به راهنما کار نمی‌کند کخ البته مشکل خاصی نیست و با چند تغییر کوچک حل می‌شود.
کد زیر

```
"require": {
  "pamenary/LaravelSms": "dev-master"
},
```
باید به این صورت اصلاح شود
```
"require": {
  "pamenary/laravel-sms": "dev-master"
},
```
تابع sendSMS یک تابع استاتیک نیست و باید  این تکه کد 
```
Sms::sendSMS(['09136000415', '09361265987'], 'text mesage'); 
```
از راهنما حذف و این کد
```
$sms = new Sms();
$sms->sendSMS(['09123456789'], 'text message');
```
استفاده شود
در ضمن باید از 
```
use Pamenary\LaravelSms\Sms;
```
نیز استفاده کرد.
با تشکر از شما به خاطر این بسته کاربردی

**Comment by pishguy** [comment]
@mojtaba82 

آره دقیقا. مستندات یه بسته به این کوچیکی با این همه اشتباه واقعا داغونه

**Comment by pamenary** [comment]
> راهنما بروز نیست و این بسته با توجه به راهنما کار نمی‌کند کخ البته مشکل خاصی نیست و با چند تغییر کوچک حل می‌شود.
> کد زیر
> 
> ```
> "require": {
>   "pamenary/LaravelSms": "dev-master"
> },
> ```
> 
> باید به این صورت اصلاح شود
> 
> ```
> "require": {
>   "pamenary/laravel-sms": "dev-master"
> },
> ```
> 
> تابع sendSMS یک تابع استاتیک نیست و باید این تکه کد
> 
> ```
> Sms::sendSMS(['09136000415', '09361265987'], 'text mesage'); 
> ```
> 
> از راهنما حذف و این کد
> 
> ```
> $sms = new Sms();
> $sms->sendSMS(['09123456789'], 'text message');
> ```
> 
> استفاده شود
> در ضمن باید از
> 
> ```
> use Pamenary\LaravelSms\Sms;
> ```
> 
> نیز استفاده کرد.
> با تشکر از شما به خاطر این بسته کاربردی

ممنون
راهنما بروزرسانی شد.
